site_name: Mynewt
site_url: http://mynewt.incubator.apache.org/index.html

pages:
- Home: 'index.md'
- Get Started:
    - 'Newt Concepts': 'get_started/newt_concepts.md'
    - 'Blinky, The First Project': 'get_started/project1.md'
    - 'How to edit docs': 'get_started/how_to_edit_docs.md'
    - 'Sample doc to edit': 'get_started/try_markdown.md'
- Get Acclimated:
    - 'Understanding Newt Terms': 'get_acclimated/vocabulary.md'
    - 'Project 2': 'get_acclimated/project2.md'
    - 'Project 3': 'get_acclimated/project3.md'
- Newt Tool:
    - 'Command structure': 'newt/newt_ops.md'
    - 'Command list': 'newt/newt_tool_reference.md'
- Mynewt OS:
    - 'Overview': 'os/mynewt_os.md'
    - 'Scheduler/Context Switching': 'os/context_switch.md'
    - 'Time': 'os/time.md'
    - 'Tasks': 'os/task.md'
    - 'Event Queues': 'os/event_queue.md'
    - 'Semaphores': 'os/semaphore.md'
    - 'Mutexes': 'os/mutex.md'
    - 'Memory Pools': 'os/memory_pool.md'
    - 'Heap': 'os/heap.md'
    - 'Mbufs': 'os/mbufs.md'
    - 'Sanity': 'os/sanity.md'
    - 'Callout Functions': 'os/callout.md'
    - 'Porting to other Platforms': 'os/port_os.md'
- Chapter5 - Modules:
    - 'Console': 'modules/console.md'
    - 'Shell': 'modules/shell.md'
    - 'Bootloader': 'modules/bootloader.md'
    - 'File System': 'modules/filesystem.md'
    - 'Test Utilities': 'modules/testutil.md'
- Chapter6 - Packaging it:
    - 'Creating Packages': 'packaging/dist.md'

markdown_extensions:
    - toc:
        permalink: true
    - sane_lists
    
theme: readthedocs 
extra_css: [extra.css]
