site_name: Mynewt
site_url: http://mynewt.incubator.apache.org/index.html

pages:
- Home: 'index.md'
- Chapter1 - Get Started:
    - 'Newt Concepts': 'chapter1/newt_concepts.md'
    - 'Blinky, The First Project': 'chapter1/project1.md'
    - 'How to edit docs': 'chapter1/how_to_edit_docs.md'
    - 'Sample doc to edit': 'chapter1/try_markdown.md'
- Chapter2 - Get Acclimated:
    - 'Understanding Newt Terms': 'chapter2/vocabulary.md'
    - 'Project 2': 'chapter2/project2.md'
    - 'Project 3': 'chapter2/project3.md'
- Chapter3 - Newt Tool:
    - 'Command structure': 'chapter3/newt_ops.md'
    - 'Command list': 'chapter3/newt_tool_reference.md'
- Chapter4 - Newt OS:
    - 'Overview': 'chapter4/mynewt_os.md'
    - 'Scheduler/Context Switching': 'chapter4/context_switch.md'
    - 'Time': 'chapter4/time.md'
    - 'Tasks': 'chapter4/task.md'
    - 'Event Queues': 'chapter4/event_queue.md'
    - 'Semaphores': 'chapter4/semaphore.md'
    - 'Mutexes': 'chapter4/mutex.md'
    - 'Memory Pools': 'chapter4/memory_pool.md'
    - 'Heap': 'chapter4/heap.md'
    - 'Mbufs': 'chapter4/mbufs.md'
    - 'Sanity': 'chapter4/sanity.md'
    - 'Porting to other Platforms': 'chapter4/port_os.md'
- Chapter5 - Modules:
    - 'Console': 'chapter5/console.md'
    - 'Shell': 'chapter5/shell.md'
    - 'Bootloader': 'chapter5/bootloader.md'
    - 'File System': 'chapter5/filesystem.md'
    - 'Test Utilities': 'chapter5/testutil.md'
- Chapter6 - Packaging it:
    - 'Creating Packages': 'chapter6/dist.md'

markdown_extensions:
    - toc:
        permalink: true
    - sane_lists
    
theme: readthedocs
extra_css: [extra.css]
