site_name: Apache Mynewt
site_url: http://mynewt.incubator.apache.org

theme_dir: 'custom-theme'

pages:
- Home: 'index.md'
- Documentation: 'documentation.md'
- Download: 'download.md'
- Community: 'community.md'
- Events: 'events.md'
- Chapter 1 - Get Started:
    - 'Newt Concepts': 'get_started/newt_concepts.md'
    - 'Blinky, The First Project': 'get_started/project1.md'
    - 'How to edit docs': 'get_started/how_to_edit_docs.md'
    - 'Sample doc to edit': 'get_started/try_markdown.md'
- Chapter 2 - Get Acclimated:
    - 'Understanding Newt Terms': 'get_acclimated/vocabulary.md'
    - 'Project 2': 'get_acclimated/project2.md'
    - 'Project 3': 'get_acclimated/project3.md'
- Chapter 3 - Newt Tool:
    - 'Command structure': 'newt/newt_ops.md'
    - 'Command list': 'newt/newt_tool_reference.md'
- Chapter 4 - Mynewt OS:
    - 'Overview': 'os/mynewt_os.md'
    - 'Scheduler/Context Switching': 'os/context_switch.md'
    - 'Time': 'os/time.md'
    - 'Tasks': 'os/task.md'
    - 'Event Queues': 'os/event_queue.md'
    - 'Semaphores': 'os/semaphore.md'
    - 'Mutexes': 'os/mutex.md'
    - 'Memory Pools': 'os/memory_pool.md'
    - 'Heap': 'os/heap.md'
    - 'Mbufs': 'os/mbufs.md'
    - 'Sanity': 'os/sanity.md'
    - 'Callout Functions': 'os/callout.md'
    - 'Porting to other Platforms': 'os/port_os.md'
- Chapter 5 - Modules:
    - 'Console': 'modules/console.md'
    - 'Shell': 'modules/shell.md'
    - 'Bootloader': 'modules/bootloader.md'
    - 'File System Abstraction': 'modules/filesystem.md'
    - 'Newtron Flash File System': 'modules/nffs.md'
    - 'Test Utilities': 'modules/testutil.md'
    - 'Image Manager': 'modules/imgmgr.md'
    - 'Baselibc library': 'modules/baselibc.md'
    - 'Embedded Lua': 'modules/elua.md'
    - 'JSON': 'modules/json.md'
- Chapter 6 - Newt Manager:
    - 'Overview': 'newtmgr/overview.md'
    - 'Protocol': 'newtmgr/protocol.md'
    - 'Project Slinky': 'newtmgr/project-slinky.md'
- Chapter 7 - Packaging it:
    - 'Creating Packages': 'packaging/dist.md'

markdown_extensions:
    - toc:
        permalink: true
    - sane_lists

extra:
    chapters:
        Chapter 1 - Get Started: 'The chapter organization is outlined below. Each chapter will include one or more tutorials for hands-on experience with the material in each chapter.'
        Chapter 2 - Get Acclimated: 'Delves deeper into the concepts crucial to the software development effort.'
        Chapter 3 - Newt Tool: 'Describes the command structure and details all the available commands to help you with your project.'
        Chapter 4 - Mynewt OS: 'Provides an overview of the features available and how to customize for your hardware and software application.'
        Chapter 5 - Modules: 'Lays out all the available modules such as HAL (Hardware Abstraction Layer), console, le system, networking stacks, and other middleware components.'
        Chapter 6 - Packaging it: 'Packages for distribution delineates the process of creating complete packages to load on your embedded device to get it up, connected, and ready for remote management.'
    events:
        event 1:
            title: 'See us at Bluetooth World!'
            description: 'Find out more about our open-source offering at this event featuring the best of IoT innovations powered by Bluetooth'
            location: "Levi's Stadium, CA, USA"
            date: 'March 15 - 16, 2016'
        event 2:
            title: 'Internet of Things World'
            description: 'Check out our product at the largest and most comprehensive IoT event on the market.'
            location: "Moscone Center, San Francisco, CA, USA"
            date: 'May 10 - 12, 2016'

copyright: 'Copyright &copy; 2015 The Apache Software Foundation, Licensed under the Apache License, Version 2.0 Apache and the Apache feather logo are trademarks of The Apache Software Foundation.<br>The Apache Software Foundation Apache Incubator'

google_analytics: ['UA-72162311-1', 'mynewt.incubator.apache.org']
