site_name: Mynewt

pages:
- Doc Home: index.md
- Getting Started:
    - 'Newt Concepts': 'chapter1/newt_concepts.md'
    - 'Blinky, The First Project': 'chapter1/project1.md'
- Getting Acclimated:
    - 'Understanding Newt Terms': 'chapter2/vocabulary.md'
    - 'Project 2': 'chapter2/project2.md'
    - 'Project 3': 'chapter2/project3.md'
- Newt tool Reference:
    - 'Command structure': 'chapter3/newt_ops.md'
    - 'Command list': 'chapter3/newt_tool_reference.md'

markdown_extensions:
    - toc:
        permalink: true
    - admonition:
    
theme: mkdocs
