site_name: Apache Mynewt
site_url: http://mynewt.incubator.apache.org

theme_dir: 'custom-theme'

pages:
- Home: 'index.md'
- Documentation: 'documentation.md'
- Download: 'download.md'
- Community: 'community.md'
- Events: 'events.md'
- Chapter 1 - Get Started:
    - 'Newt Concepts': 'get_started/newt_concepts.md'
    - 'Blinky, The First Project': 'get_started/project1.md'
    - 'How to edit docs': 'get_started/how_to_edit_docs.md'
    - 'Sample doc to edit': 'get_started/try_markdown.md'
- Chapter 2 - Get Acclimated:
    - 'Understanding Newt Terms': 'get_acclimated/vocabulary.md'
    - 'Project 2': 'get_acclimated/project2.md'
    - 'Project 3': 'get_acclimated/project3.md'
- Chapter 3 - Newt Tool:
    - 'Command structure': 'newt/newt_ops.md'
    - 'Command list': 'newt/newt_tool_reference.md'
- Chapter 4 - Mynewt OS:
    - 'Overview': 'os/mynewt_os.md'
    - 'Scheduler/Context Switching': 'os/context_switch.md'
    - 'Time': 'os/time.md'
    - 'Tasks': 'os/task.md'
    - 'Event Queues': 'os/event_queue.md'
    - 'Semaphores': 'os/semaphore.md'
    - 'Mutexes': 'os/mutex.md'
    - 'Memory Pools': 'os/memory_pool.md'
    - 'Heap': 'os/heap.md'
    - 'Mbufs': 'os/mbufs.md'
    - 'Sanity': 'os/sanity.md'
    - 'Callout Functions': 'os/callout.md'
    - 'Porting to other Platforms': 'os/port_os.md'
- Chapter 5 - Modules:
    - Console:  
       - 'console overview': 'modules/console/console.md'
       - 'console_add_char': 'modules/console/console_add_char.md'
       - 'console_blocking_mode': 'modules/console/console_blocking_mode.md'
       - 'console_blocking_tx': 'modules/console/console_blocking_tx.md'
       - 'console_init': 'modules/console/console_init.md'
       - 'console_printf': 'modules/console/console_printf.md'
       - 'console_pull_char': 'modules/console/console_pull_char.md'
       - 'console_pull_char_head': 'modules/console/console_pull_char_head.md'
       - 'console_queue_char': 'modules/console/console_queue_char.md'
       - 'console_read': 'modules/console/console_read.md'
       - 'console_rx_char': 'modules/console/console_rx_char.md'
       - 'console_tx_char': 'modules/console/console_tx_char.md'
       - 'console_write': 'modules/console/console_write.md'
    - Shell: 
       - 'shell overview': 'modules/shell/shell.md'
       - 'shell_cmd': 'modules/shell/shell_cmd.md'
       - 'shell_cmd_list_lock': 'modules/shell/shell_cmd_list_lock.md'
       - 'shell_cmd_list_unlock': 'modules/shell/shell_cmd_list_unlock.md'
       - 'shell_cmd_register': 'modules/shell/shell_cmd_register.md'
       - 'shell_console_rx_cb': 'modules/shell/shell_console_rx_cb.md'
       - 'shell_echo_cmd': 'modules/shell/shell_echo_cmd.md'
       - 'shell_help_cmd': 'modules/shell/shell_help_cmd.md'
       - 'shell_nlip_input_register': 'modules/shell/shell_nlip_input_register.md'
       - 'shell_nlip_mqueue_process': 'modules/shell/shell_nlip_mqueue_process.md'
       - 'shell_nlip_mtx': 'modules/shell/shell_nlip_mtx.md'
       - 'shell_nlip_output': 'modules/shell/shell_nlip_output.md'
       - 'shell_nlip_process': 'modules/shell/shell_nlip_process.md'
       - 'shell_os_mpool_display_cmd': 'modules/shell/shell_os_mpool_display_cmd.md'
       - 'shell_os_tasks_display_cmd': 'modules/shell/shell_os_tasks_display_cmd.md'
       - 'shell_process_command': 'modules/shell/shell_process_command.md'
       - 'shell_read_console': 'modules/shell/shell_read_console.md'
       - 'shell_task_func': 'modules/shell/shell_task_func.md'
       - 'shell_task_init': 'modules/shell/shell_task_init.md'
    - Bootloader: 
       - 'bootloader overview': 'modules/bootloader/bootloader.md'
       - 'boot_build_status': 'modules/bootloader/boot_build_status.md'
       - 'boot_build_status_one': 'modules/bootloader/boot_build_status_one.md'
       - 'boot_clear_status': 'modules/bootloader/boot_clear_status.md'
       - 'boot_copy_area': 'modules/bootloader/boot_copy_area.md'
       - 'boot_copy_image': 'modules/bootloader/boot_copy_image.md'
       - 'boot_erase_area': 'modules/bootloader/boot_erase_area.md'
       - 'boot_fill_slot': 'modules/bootloader/boot_fill_slot.md'
       - 'boot_find_image_area_idx': 'modules/bootloader/boot_find_image_area_idx.md'
       - 'boot_find_image_part': 'modules/bootloader/boot_find_image_part.md'
       - 'boot_find_image_slot': 'modules/bootloader/boot_find_image_slot.md'
       - 'boot_go': 'modules/bootloader/boot_go.md'
       - 'boot_init_flash': 'modules/bootloader/boot_init_flash.md'
       - 'boot_move_area': 'modules/bootloader/boot_move_area.md'
       - 'boot_read_image_header': 'modules/bootloader/boot_read_image_header.md'
       - 'boot_read_image_headers': 'modules/bootloader/boot_read_image_headers.md'
       - 'boot_read_status': 'modules/bootloader/boot_read_status.md'
       - 'boot_select_image_slot': 'modules/bootloader/boot_select_image_slot.md'
       - 'boot_slot_addr': 'modules/bootloader/boot_slot_addr.md'
       - 'boot_slot_to_area_idx': 'modules/bootloader/boot_slot_to_area_idx.md'
       - 'boot_swap_areas': 'modules/bootloader/boot_swap_areas.md'
       - 'boot_vect_delete_main': 'modules/bootloader/boot_vect_delete_main.md'
       - 'boot_vect_delete_test': 'modules/bootloader/boot_vect_delete_test.md'
       - 'boot_vect_read_main': 'modules/bootloader/boot_vect_read_main.md'
       - 'boot_vect_read_one': 'modules/bootloader/boot_vect_read_one.md'
       - 'boot_vect_read_test': 'modules/bootloader/boot_vect_read_test.md'
       - 'boot_write_status': 'modules/bootloader/boot_write_status.md'
    - 'File System Abstraction': 'modules/filesystem.md'
    - 'Newtron Flash File System': 'modules/nffs.md'
    - Test Utilities:
       - 'testutil overview': 'modules/testutil/testutil.md'
       - 'tu_case_abort': 'modules/testutil/tu_case_abort.md'
       - 'tu_case_append_assert_msg': 'modules/testutil/tu_case_append_assert_msg.md'
       - 'tu_case_append_buf': 'modules/testutil/tu_case_append_buf.md'
       - 'tu_case_append_file_info': 'modules/testutil/tu_case_append_file_info.md'
       - 'tu_case_append_manual_pass_msg': 'modules/testutil/tu_case_append_manual_pass_msg.md'
       - 'tu_case_complete': 'modules/testutil/tu_case_complete.md'
       - 'tu_case_fail_assert': 'modules/testutil/tu_case_fail_assert.md'
       - 'tu_case_init': 'modules/testutil/tu_case_init.md'
       - 'tu_case_pass_manual': 'modules/testutil/tu_case_pass_manual.md'
       - 'tu_case_set_name': 'modules/testutil/tu_case_set_name.md'
       - 'tu_case_vappend_buf': 'modules/testutil/tu_case_vappend_buf.md'
       - 'tu_case_write_fail_buf': 'modules/testutil/tu_case_write_fail_buf.md'
       - 'tu_case_write_pass_auto': 'modules/testutil/tu_case_write_pass_auto.md'
       - 'tu_case_write_pass_buf': 'modules/testutil/tu_case_write_pass_buf.md'
       - 'tu_init': 'modules/testutil/tu_init.md'
       - 'tu_restart': 'modules/testutil/tu_restart.md'
       - 'tu_suite_init': 'modules/testutil/tu_suite_init.md'
       - 'tu_suite_set_name': 'modules/testutil/tu_suite_set_name.md'
    - Image Manager:
       - 'imgmgr overview': 'modules/imgmgr/imgmgr.md'
       - 'imgmgr_module_init': 'modules/imgmgr/imgmgr_module_init.md'
       - 'imgr_boot_read': 'modules/imgmgr/imgr_boot_read.md'
       - 'imgr_boot_write': 'modules/imgmgr/imgr_boot_write.md'
       - 'imgr_file_download': 'modules/imgmgr/imgr_file_download.md'
       - 'imgr_file_upload': 'modules/imgmgr/imgr_file_upload.md'
       - 'imgr_list': 'modules/imgmgr/imgr_list.md'
       - 'imgr_noop': 'modules/imgmgr/imgr_noop.md'
       - 'imgr_read_file': 'modules/imgmgr/imgr_read_file.md'
       - 'imgr_read_main': 'modules/imgmgr/imgr_read_main.md'
       - 'imgr_read_test': 'modules/imgmgr/imgr_read_test.md'
       - 'imgr_read_ver': 'modules/imgmgr/imgr_read_ver.md'
       - 'imgr_upload': 'modules/imgmgr/imgr_upload.md'
       - 'imgr_ver_jsonstr': 'modules/imgmgr/imgr_ver_jsonstr.md'
       - 'imgr_ver_parse': 'modules/imgmgr/imgr_ver_parse.md'
       - 'imgr_ver_str': 'modules/imgmgr/imgr_ver_str.md'
       - 'imgr_write_file': 'modules/imgmgr/imgr_write_file.md'
    - 'Baselibc library': 'modules/baselibc.md'
    - 'Embedded Lua': 'modules/elua.md'
    - JSON: 
       - 'JSON overview': 'modules/json/json.md'
       - 'json_encode_object_entry': 'modules/json/json_encode_object_entry.md'
       - 'json_encode_object_finish': 'modules/json/json_encode_object_finish.md'
       - 'json_encode_object_key': 'modules/json/json_encode_object_key.md'
       - 'json_encode_object_start': 'modules/json/json_encode_object_start.md'
       - 'json_encode_value': 'modules/json/json_encode_value.md'
       - 'json_internal_read_object': 'modules/json/json_internal_read_object.md'
       - 'json_read_array': 'modules/json/json_read_array.md'
       - 'json_read_object': 'modules/json/json_read_object.md'
       - 'json_target_address': 'modules/json/json_target_address.md'
- Chapter 6 - Newt Manager:
    - 'Overview': 'newtmgr/overview.md'
    - 'Protocol': 'newtmgr/protocol.md'
    - 'Project Slinky': 'newtmgr/project-slinky.md'
- Chapter 7 - Packaging it:
    - 'Creating Packages': 'packaging/dist.md'

markdown_extensions:
    - toc:
        permalink: true
    - sane_lists

extra:
    chapters:
        Chapter 1 - Get Started: 'The chapter organization is outlined below. Each chapter will include one or more tutorials for hands-on experience with the material in each chapter.'
        Chapter 2 - Get Acclimated: 'Delves deeper into the concepts crucial to the software development effort.'
        Chapter 3 - Newt Tool: 'Describes the command structure and details all the available commands to help you with your project.'
        Chapter 4 - Mynewt OS: 'Provides an overview of the features available and how to customize for your hardware and software application.'
        Chapter 5 - Modules: 'Lays out all the available modules such as HAL (Hardware Abstraction Layer), console, le system, networking stacks, and other middleware components.'
        Chapter 6 - Packaging it: 'Packages for distribution delineates the process of creating complete packages to load on your embedded device to get it up, connected, and ready for remote management.'
    events:
        event 1:
            title: 'See us at Bluetooth World!'
            description: 'Find out more about our open-source offering at this event featuring the best of IoT innovations powered by Bluetooth'
            location: "Levi's Stadium, CA, USA"
            date: 'March 15 - 16, 2016'
        event 2:
            title: 'Internet of Things World'
            description: 'Check out our product at the largest and most comprehensive IoT event on the market.'
            location: "Moscone Center, San Francisco, CA, USA"
            date: 'May 10 - 12, 2016'

copyright: 'Copyright &copy; 2015 The Apache Software Foundation, Licensed under the Apache License, Version 2.0 Apache and the Apache feather logo are trademarks of The Apache Software Foundation.<br>The Apache Software Foundation Apache Incubator'

google_analytics: ['UA-72162311-1', 'mynewt.incubator.apache.org']
